CREATE TABLE users (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `password` VARCHAR(32) DEFAULT NULL,
  `email` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) DEFAULT NULL,
  `created_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  INDEX email_index (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
