CREATE TABLE users (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `auth_id` INT UNSIGNED NOT NULL,

  FOREIGN KEY (auth_id) REFERENCES auth(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
